services:
  backend:
    image: punschkrapferl23/codeparser-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./repos:/app/repos
    environment:
      OLLAMA_HOST: http://host.docker.internal:11434
      MODEL_NAME: mistral:latest

  frontend:
    image: punschkrapferl23/codeparser-frontend:latest
    ports:
      - "4200:80"
    depends_on:
      - backend
